### ISSUE TITLE
Rename "ends at" to something clearer

### ISSUE THREAD

**Issue by baedrik** [stakeordie/scrt-auction#23]
There appears to be some confusion about why an auction stays open and accepts bids after the ends at time.  Since the ends at time is only when ANYONE can close the auction, not actually a forced time to close, maybe we should just label the time "anyone can close at" or something similar (but more eloquent lol)

**Comment by cankisagun** [comment]
we can add a button to finish the auction similar to bid, maybe smaller in font so it's doesn't distract from the main CTA
![image](https://user-images.githubusercontent.com/15679491/105763158-749ef280-5f23-11eb-845a-28f5815bfc8c.png)

**Comment by the-dusky** [comment]
It is an interesting concept that seems unique to a decentralized approach. The idea that "anyone can close" is a bit of a hack correct. I it didn't require a TX to close an auctions, say in a centralized app, then it would just end at this time, am I correct? I mention this because in coming up with the right language we need to think about how people understand traditional applications to work. Or include educational to help define terms. This seems to me like it should be something like, "Close-able at".  And then have a (what is this?) link next to it that opens a modal"

**Comment by baedrik** [comment]
Yes, it is just because contracts can't call themselves, so something has to generate the tx to close it, so there is no way for the contract itself to guarantee that it will close at the specified time.  One way to automate it, would be if the UI generated an address/mnemonic so that it wouldn't need Keplr approval when it generates the tx.  The seller would have to leave the UI running, and would have to send some SCRT to the UI address to be used for gas, but the UI would be able to auto-close any of the seller's auctions after closing time

**Comment by baedrik** [comment]
But because there is no guarantee that the seller will leave the UI running, we would still need the "what is this ?" you describe above

**Comment by cankisagun** [comment]
No need to automate it. This is how all decentralized apps work. 
However Baedrick I think your suggestion is not really helpful - it's more confusing TBH. Let's keep it as is

**Comment by baedrik** [comment]
Works for me.  In the discord #secret-testnet channel, uxt seems to think that "ends at" is very confusing for people.  I don't find it confusing because I'm starting with a lot of inside knowledge, so I was just creating the issue to address his concerns

**Comment by the-dusky** [comment]
Changed to Target Close with a tooltip explination
