### ISSUE TITLE
Seller shouldn't be able to bid on their own auction

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#24]
The Bid button should be disabled or not visible for an auction where the user is a seller.

![image](https://user-images.githubusercontent.com/436905/105762676-b0858800-5f22-11eb-9b0e-936108527616.png)

Maybe change "Bid" to "View"? I haven't gotten far enough to see if that makes sense though. Oh wait, the seller can change the minimum bid from clicking on that button so maybe it should say "Manage" or "Edit" instead of "Bid".

And if it's the seller editing their auction, leave out the fields and button for placing a bid.

![image](https://user-images.githubusercontent.com/436905/105762996-2db0fd00-5f23-11eb-83a1-53c2452aee57.png)

**Comment by the-dusky** [comment]
Hey Laura,

This is not the case. The seller can bid on their own auction as a way to hedge against accepting too low a bid. This is a contract discussion point.

**Comment by lauraweindorf** [comment]
oh that's interesting, I did not realize that. Thanks Sandy!

**Comment by baedrik** [comment]
@lauraweindorf
Yes, as Sandy explained, this is intentional.  It allows the seller to protect himself.  For example, if the price moves against him, even if he raises the minimum bid, we will not reject existing bids below that threshold (that were valid before the change).  That would not be fair to the early bidders who should still at least have a chance to win.  But if the seller wants to guarantee his tokens won't be sold for less than the new minimum, he could place a bid at the new minimum.  That insurance costs him in that if no one bids higher, he will be paying the gas fees to close to just swap coins with himself, but he should be allowed that option if he wants it.  Besides, anyone who would do this, would just bid with a second address if the seller address was blocked, so no reason to force that

**Comment by lauraweindorf** [comment]
Gosh, that is not making sense to me. It seems like it would be easier to let the seller increase the minimum bid and to notify earlier bidders so they can choose to increase their bids, if desired. Making the seller place a bid on his own auction seems like a lot ... and I imagine that not all sellers would be able to place a bid if they've already locked up a large portion of their tokens in the auction contract.

**Comment by lauraweindorf** [comment]
Not trying to be difficult! This is just becoming a bit of a head-scratcher for me :-O.

**Comment by baedrik** [comment]
They won't have any of the bidding tokens locked unless they already have placed a bid.  They would only have sell tokens locked otherwise

**Comment by baedrik** [comment]
Just on principle, I don't think that any bids that were made under the original terms of agreement on the minimum bid, should be allowed to be rejected after the fact

**Comment by lauraweindorf** [comment]
Ah so if I create an auction to sell 10k SCRT for sETH, my SCRT is locked in the contract and to protect myself as a seller after I've increased the minimum bid, I would place a bid locking up sETH. So for a seller that didn't have the sETH needed to place a bid on his own auction, increasing the minimum bid would still be a viable option because someone might come along later and place a higher bid. The seller just isn't as protected as when he places a bid himself..

Thanks for the explanations, Baedrik!

**Comment by baedrik** [comment]
That is correct (except both tokens have to be SNIP20, so it would be sSCRT instead of SCRT).

But yes, if you are selling sSCRT for sETH, you are locking up the sSCRT that is being sold.  If you raise the minimum bid, but do not have any sETH to place a bid, you have to hope that at least one person places a bid after you changed the minimum, because you know any new bids will be at least that amount.  If you want the insurance that your sSCRT won't be sold for less than the new minimum bid, it is your responsibility to "buy insurance" by placing a bid at the new minimum

**Comment by cankisagun** [comment]
@the-dusky let's add an explanation underneath bidding in your own auction - this would need to determine that Keplr is the seller. 

You may want to make a bid to your own auction during times of high volatility to ensure that the initial asking price is not too low. If there were bids prior to changing the asking price, these bids will remain active and can only be overwritten by a higher bid

**Comment by the-dusky** [comment]
I am going to open a new issue about this.
