### ISSUE TITLE
Auction "description" is not getting displayed

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#31]
I created this auction with a description, but it's empty on the Bid page:

![image](https://user-images.githubusercontent.com/436905/105776080-eda74580-5f35-11eb-9bb3-b7580e71cf62.png)

Also, it would be nice to see the description on the Grid and List view of the auctions too.

![image](https://user-images.githubusercontent.com/436905/105776170-19c2c680-5f36-11eb-9c42-b2dfce9b1931.png)

![image](https://user-images.githubusercontent.com/436905/105776273-45de4780-5f36-11eb-94d4-3cae83329730.png)

**Comment by baedrik** [comment]
@the-dusky The problem appears to be that the UI does not send the "description" field when creating an auction.

If I create an auction with a description in the UI, neither the UI nor secretcli shows a description.

If I create an auction with a description through secretcli, both the UI and secretcli correctly shows the description

**Comment by baedrik** [comment]
@lauraweindorf It would be best to not display the description from a list, because to do it from the list, the factory will have to duplicate the information.  Since the factory has to store the information for every auction ever created, it is best to limit how much duplication of data there is to minimize the gas cost of maintaining factory-lifetime lists...especially with something like a free-form description that can be very long.  If we think the description would be critical to see from the list instead of waiting until you go to the auction page, it could be added.  But we should be sure it is critical.

**Comment by cankisagun** [comment]
This is annoying but in order to ship fast, I would remove description from the UI completely for this version and get to this problem after the release. 

I'm not very convinced that description is a critical feature now. Will become with NFTs
