### ISSUE TITLE
Extending an auction seems to close it right away instead of letting it stay open for the specified amount of time

### ISSUE THREAD

**Issue by lauraweindorf** [stakeordie/scrt-auction#34]
I did the extend and clicked close with options, using 1 day. The end date/time wasn't updated to the next day and the display then updated to show that the contract was closed.

![image](https://user-images.githubusercontent.com/436905/105778189-dbc7a180-5f39-11eb-8773-83fd0a3b27b5.png)

**Comment by baedrik** [comment]
@lauraweindorf
If you try to extend an auction and there are bids, it will close the auction and swap with the winner.  The seller is not allowed  to arbitrarily keep postponing the closing time, because that would be unfair to existing bidders.  If the price moved against the seller, he could just postpone it forever hoping that eventually they all retract their bid and he can close to get his sell tokens back, or he postpones until there is a price dump and then he is ok with the bids that were placed earlier.

If it isn't clear, there should be a flow that makes it clear that you are closing the auction, but if there are no bids you would like to update the closing time or minimum just so you don't have to create a new auction

**Comment by baedrik** [comment]
The option to extend is only shown after the user clicks code auction, so I think the flow should reveal that they are closing the auction and only extending if there are no bids

**Comment by cankisagun** [comment]
I addressed this in issue #46

**Comment by lauraweindorf** [comment]
in additional testing tonight I'm not getting the option to close and extend an auction I just created for an auction with no bids fyi. I don't know if that's because there were code changes ...

**Comment by lauraweindorf** [comment]
@baedrik what I was attempting to do in this issue originally was to verify that the auction "extend" functionality actually updated the ends_at time to reflect the extension time and that the auction was then closed. From what I could see the auction was closing right away. Now I'm not getting the option to extend so I can't verify that this was actually an issue. It appeared to be, but :shrug: I can't reproduce it anymore 😄.

**Comment by baedrik** [comment]
@lauraweindorf from the screenshot in the original comment, it says that the auction has 1 or more bids.  That is why it closed right away.  That is the intended functionality when there are bids

**Comment by lauraweindorf** [comment]
Sorry for the confusion @baedrik. I actually posted the wrong screenshot 😕. I tried the extend on an auction with 0 bids. But since I can't reproduce it anymore 🤷. I guess this issue should be closed?
